### ISSUE TITLE
Document 3rd party usage

### ISSUE THREAD

**Issue by 89z** [BochilTeam/scraper#11]
It seems Instagram is being pulled from a different server:

https://github.com/BochilTeam/scraper/blob/704a8652c80eb0796c0f6c461d65dcfd7f42e84b/src/social-media/instagram.ts#L18-L28

I think that should be documented

**Comment by BochilGaming** [comment]
> It seems Instagram is being pulled from a different server:
> 
> https://github.com/BochilTeam/scraper/blob/704a8652c80eb0796c0f6c461d65dcfd7f42e84b/src/social-media/instagram.ts#L18-L28
> 
> I think that should be documented

sorry for the short documentation :v
