### ISSUE TITLE
[REQ] Google It

### ISSUE THREAD

**Issue by ThisMe124** [BochilTeam/scraper#2]
Dia Malah Result []

**Comment by BochilGaming** [comment]
> Dia Malah Result []

yang mau kamu download bentuknya apa?, rell, video, image?

**Comment by ThisMe124** [comment]
> > Dia Malah Result []
> 
> yang mau kamu download bentuknya apa?, rell, video, image?

Gak Bisa Support semuanya? Waktu itu sayah mau Download gambar eh result nya []

**Comment by ThisMe124** [comment]
Btw InstagramStory Juga Sama Result nya [] padahl udah benar usernamenya

**Comment by BochilGaming** [comment]
ok"

**Comment by BochilGaming** [comment]
[web](https://snapinsta.app) nya error ternyata :v

**Comment by ThisMe124** [comment]
👌

**Comment by ThisMe124** [comment]
> [web](https://snapinsta.app) nya error ternyata :v

Pantes :v

**Comment by ThisMe124** [comment]
Btw tiktokdlnya emang gitu yak Dia Gak Response Gitu Kadang²

**Comment by BochilGaming** [comment]
> Btw tiktokdlnya emang gitu yak Dia Gak Response Gitu Kadang²

Di versi terbaru ada 2 function yaitu ```tiktokdl``` dan ```tiktokdlv2``` jadi kalau error coba pakek yang lain

**Comment by ThisMe124** [comment]
Okeh

**Comment by ThisMe124** [comment]
Btw Request Google Image nya ada textnya gitu di bawal url gambarnya :v

**Comment by BochilGaming** [comment]
> Btw Request Google Image nya ada textnya gitu di bawal url gambarnya :v

ok"

**Comment by ThisMe124** [comment]
Wdoh

**Comment by BochilGaming** [comment]
> Wdoh

done di versi [0.0.4](https://github.com/BochilTeam/scraper/tree/0.0.4) tapi kadang to many request
