### ISSUE TITLE
Error: Cannot find execute code

### ISSUE THREAD

**Issue by jacktheboss220** [BochilTeam/scraper#84]
/*js-response*/(function(){
  function del(){while(document.body.firstChild){document.body.removeChild(document.body.firstChild);}};

if(window.location.hostname.search(/(?:^|\.|@)(savefrom\.net|sfrom\.net|ssyoutube\.com)$/i) == -1) {
  alert('Please go to http://savefrom.net/ to get direct links');
  del();
  return;
}
  function showResult(){
    var success = false;
    try {
      var d = window.parent.document;
      if(d && d.getElementById) {
        var e = d.getElementById('sf_result');
        if(e && e.innerHTML) {
          window.parent.sf.finishRequest(true);;
          e.innerHTML = '';
          window.parent.sf.result.showEmptyResult({"html":"Something went wrong. Please try to reload the page or use another browser.","invalid_request":true,"resource":"","success":false,"source_url":"https://www.instagram.com/p/CvFbwPqRxd3"},false,true,false);;
          window.parent.sf.enableElement('sf_submit', true);
          success=true;
        }
      }
    } catch(err){}
    del();
    if(!success) {
      var alt = '';
      if(alt) alert(alt);
    }
  }
  showResult();
})();/*js-response*/

its not working. please take a look,

url- https://www.instagram.com/p/CvFbwPqRxd3

**Comment by noxzym** [comment]
I believe that we need to put `ts`, `_ts`, `_tsc`, and `_s` into the request body right now
![image](https://github.com/BochilTeam/scraper/assets/67855694/dcb3ceba-add1-41a9-aa5b-e5c6aa69ee67)

**Comment by BochilGaming** [comment]
Try to use @bochilteam/scraper 5.0.1 version
