### ISSUE TITLE
Scrape Error

### ISSUE THREAD

**Issue by Nexov25** [BochilTeam/scraper#85]
.igdl error : ScraperError: Cannot find execute code
/*js-response*/(function(){
  function del(){while(document.body.firstChild){document.body.removeChild(document.body.firstChild);}};
  
if(window.location.hostname.search(/(?:^|\.|@)(savefrom\.net|sfrom\.net|ssyoutube\.com)$/i) == -1) {
  alert('Please go to http://savefrom.net/ to get direct links');
  del();
  return;
}
  function showResult(){
    var success = false;
    try {
      var d = window.parent.document;
      if(d && d.getElementById) {
        var e = d.getElementById('sf_result');
        if(e && e.innerHTML) {
          window.parent.sf.finishRequest(true);;
          e.innerHTML = '';
          window.parent.sf.result.showEmptyResult({"html":"Something went wrong. Please try to reload the page or use another browser.","invalid_request":true,"resource":"","success":false,"source_url":"https://www.instagram.com/reel/Cu1m_2sOX1N/?igshid=MzRlODBiNWFlZA=="},false,true,false);;
          window.parent.sf.enableElement('sf_submit', true);
          success=true;
        }
      }
    } catch(err){} 
    del();
    if(!success) {
      var alt = '';
      if(alt) alert(alt);
    }
  }
  showResult();
})();/*js-response*/

If this is bug pls report to https://github.com/BochilTeam/scraper

**Comment by BochilGaming** [comment]
This bug has been fixed in https://github.com/BochilTeam/scraper/commit/f1b2c90223b159cde49ab9af6881ce4636ce2b08

**Comment by BochilGaming** [comment]
Try to use @bochilteam/scraper 5.0.1 version
