### ISSUE TITLE
igstory issue

### ISSUE THREAD

**Issue by nastarrr** [BochilTeam/scraper#89]
const { instagramStory } = require('@bochilteam/scraper')
await instagramStory("Persija").then(res => {
console.log(res)
})

output:
HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1696041980886,
    socket: 1696041980887,
    lookup: 1696041980900,
    connect: 1696041980912,
    secureConnect: 1696041980929,
    upload: 1696041980929,
    response: 1696041985238,
    end: 1696041985335,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 13,
      tcp: 12,
      tls: 17,
      request: 0,
      firstByte: 4309,
      download: 97,
      total: 4449
    }
  }
}

**Comment by BochilGaming** [comment]
Try to use @bochilteam/scraper 5.0.1 version
