### ISSUE TITLE
Ytdl yMatenya error? 

### ISSUE THREAD

**Issue by ThisMe124** [BochilTeam/scraper#9]
Kenapa Gak NgeResult Link Donwloadnya?

**Comment by BochilGaming** [comment]
> Kenapa Gak NgeResult Link Donwloadnya?

ada ss error nya??, atau info yang lebih detail?

**Comment by ThisMe124** [comment]
{
  "video_id": "qEXjSGj57as",
  "title": "Apakah ini akhir perjalanan bang Luthfi ngesimp?",
  "thumbnail": "https://i.ytimg.com/vi/qEXjSGj57as/0.jpg",
  "vid": {
    "1080p": {
      "quality": "1080p",
      "fileSizeH": "33.7 MB",
      "fileSize": 33700
    },
    "720p": {
      "quality": "720p",
      "fileSizeH": "14.7 MB",
      "fileSize": 14700
    },
    "480p": {
      "quality": "480p",
      "fileSizeH": "11.8 MB",
      "fileSize": 11800
    },
    "360p": {
      "quality": "360p",
      "fileSizeH": "14.6 MB",
      "fileSize": 14600
    },
    "240p": {
      "quality": "240p",
      "fileSizeH": "8.1 MB",
      "fileSize": 8100
    },
    "144p": {
      "quality": "144p",
      "fileSizeH": "6.9 MB",
      "fileSize": 6900
    }
  },
  "audio": {
    "128kbps": {
      "quality": "128kbps",
      "fileSizeH": "5.4 MB",
      "fileSize": 5400
    }
  }
}

NgeResult Ini tanpa link downloadnya

**Comment by BochilGaming** [comment]
hmmm.....

**Comment by BochilGaming** [comment]
> { "id": "61da4835f99cc545248b4569", "v_id": "qEXjSGj57as", "thumbnail": "https://i.ytimg.com/vi/qEXjSGj57as/0.jpg", "title": "Apakah ini akhir perjalanan bang Luthfi ngesimp?", "video": { "1080p": { "quality": "1080p", "fileSizeH": "33.7 MB", "fileSize": 33700 }, "720p": { "quality": "720p", "fileSizeH": "14.7 MB", "fileSize": 14700 }, "480p": { "quality": "480p", "fileSizeH": "11.8 MB", "fileSize": 11800 }, "360p": { "quality": "360p", "fileSizeH": "14.6 MB", "fileSize": 14600 }, "240p": { "quality": "240p", "fileSizeH": "8.1 MB", "fileSize": 8100 }, "144p": { "quality": "144p", "fileSizeH": "6.9 MB", "fileSize": 6900 } }, "audio": { "128kbps": { "quality": "128kbps", "fileSizeH": "5.4 MB", "fileSize": 5400 } } }
> 
> NgeResult Ini tanpa link downloadnya

di punyaku semua nya ada download nya kok

**Comment by ThisMe124** [comment]
> > { "id": "61da4835f99cc545248b4569", "v_id": "qEXjSGj57as", "thumbnail": "https://i.ytimg.com/vi/qEXjSGj57as/0.jpg", "title": "Apakah ini akhir perjalanan bang Luthfi ngesimp?", "video": { "1080p": { "quality": "1080p", "fileSizeH": "33.7 MB", "fileSize": 33700 }, "720p": { "quality": "720p", "fileSizeH": "14.7 MB", "fileSize": 14700 }, "480p": { "quality": "480p", "fileSizeH": "11.8 MB", "fileSize": 11800 }, "360p": { "quality": "360p", "fileSizeH": "14.6 MB", "fileSize": 14600 }, "240p": { "quality": "240p", "fileSizeH": "8.1 MB", "fileSize": 8100 }, "144p": { "quality": "144p", "fileSizeH": "6.9 MB", "fileSize": 6900 } }, "audio": { "128kbps": { "quality": "128kbps", "fileSizeH": "5.4 MB", "fileSize": 5400 } } }
> > NgeResult Ini tanpa link downloadnya
> 
> di punyaku semua nya ada download nya kok

Lah aneh

**Comment by BochilGaming** [comment]
coba pakek ytdl yang versi lain

**Comment by BochilGaming** [comment]
@ThisMe124 Apakah di versi 0.0.7 masih error?

**Comment by ThisMe124** [comment]
> @ThisMe124 Apakah di versi 0.0.7 masih error?

Hmmm, Belum Saya Coba. Tapi Akan Saya Coba

**Comment by ThisMe124** [comment]
Nah dah bisa
