### ISSUE TITLE
youtubedl & youtubedlv2 error

### ISSUE THREAD

**Issue by nstar-y** [BochilTeam/scraper#92]
const { youtubedl } = require('@bochilteam/scraper')

```
(async () => {
youtubedl("https://youtube.com/watch?v=HpUcMGmZbko").then(res => {
console.log(res) })
})();
```

output: 
HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (/home/container/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1700022630672,
    socket: 1700022630672,
    lookup: 1700022630675,
    connect: 1700022630677,
    secureConnect: 1700022630681,
    upload: 1700022630681,
    response: 1700022630690,
    end: 1700022630691,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 3,
      tcp: 2,
      tls: 4,
      request: 0,
      firstByte: 9,
      download: 1,
      total: 19
    }
  }
}

youtubedl dan youtubedlv2 output na sama

**Comment by BochilGaming** [comment]
Try to use @bochilteam/scraper 5.0.1 version
