### ISSUE TITLE
(Tiktokdl) Kenapa tiba tiba error padahal jam 8 pm masih bisa di SC aku yang lain juga sama error

### ISSUE THREAD

**Issue by wither3** [BochilTeam/scraper#93]
![Screenshot_20231204_214732](https://github.com/BochilTeam/scraper/assets/84785651/93e3c04a-0394-47ef-bb37-07e71b720634)

**Comment by BochilGaming** [comment]
Apakah masih tidak bisa??

**Comment by wither3** [comment]
sudah bisa

Pada tanggal Min, 21 Jan 2024 8.11 AM, BochilGaming <
***@***.***> menulis:

**Comment by BochilGaming** [comment]
Try to use @bochilteam/scraper 5.0.1 version
