### ISSUE TITLE
facebookdl and facebookdlv2 error

### ISSUE THREAD

**Issue by Xnuvers007** [BochilTeam/scraper#94]
error:

/node_modules/zod/lib/index.mjs:538
                const error = new ZodError(ctx.common.issues);
                              ^

ZodError: [
  {
    "code": "invalid_type",
    "expected": "number",
    "received": "string",
    "path": [
      "duration"
    ],
    "message": "Expected number, received string"
  }
]
    at get error [as error] (/node_modules/zod/lib/index.mjs:538:31)
    at ZodObject.parse (/node_modules/zod/lib/index.mjs:638:22)
    at facebookdl (/node_modules/@bochilteam/scraper-sosmed/lib/esm/src/facebook.js:48:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file /index.js:14:14 {
  issues: [
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'string',
      path: [ 'duration' ],
      message: 'Expected number, received string'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'invalid_type',
      expected: 'number',
      received: 'string',
      path: [ 'duration' ],
      message: 'Expected number, received string'
    }
  ]
}

Node.js v20.0.0

```
import { facebookdl, facebookdlv2 } from '@bochilteam/scraper-sosmed'

const data = await facebookdl('https://www.facebook.com/reel/841811270967738')
console.log(data) // JSON
const data2 = await facebookdlv2('https://www.facebook.com/reel/841811270967738')
console.log(data2) // JSON
```

**Comment by Xnuvers007** [comment]
@BochilGaming Min tolong update package Npm nya, terimakasih.

**Comment by BochilGaming** [comment]
Try to use @bochilteam/scraper 5.0.1 version
