### ISSUE TITLE
Gagal dalam mendownload tiktok no wm

### ISSUE THREAD

**Issue by Armageddonz** [BochilTeam/scraper#97]
![Screenshot_2024-02-17-18-35-28-70](https://github.com/BochilTeam/scraper/assets/155276702/7f2efeab-30ca-478e-850b-73cb14dd6151)
![Screenshot_2024-02-17-18-35-10-77](https://github.com/BochilTeam/scraper/assets/155276702/9cb0ab54-4df5-4e5b-9370-6d6ad3586137)

ScraperError: Cannot find execute code/js-response/(function(){function del(){while(document.body.firstChild){document.bo dy.removeChild(document.body.firstChild);}};if(window.location.hostname.search(/(?:^|.|@)(savefrom.ne|sfrom.net|ssyoutube.com)$/1) == -1) {alert('Please go to http://savefrom.net/ to get direct links');del();return;function showResult(){var success = false;try {var d = window.parent.document;if(d && d.getElementById) {var e= d.getElementById('sf_result');if(e && e.innerHTML) {window.parent.sf.finishRequest(true);;e.innerHTML =window.parent.sf.result.showEmptyResult({"html":"Something went wrong. Please try to reload the page or use an other browser.","invalid_request":true,"resource": "", "succes s":false,"source_url":"https://vt.tiktok.com/ZSFjKtYas/"},false, true, false);;window.parent.sf.enableElement('sf_submit', true); success=true;Type a command}StartRestartStop}} } catch(err){}del();if(!success) {var alt="if(alt) alert(alt);} }showResult();})();/js-response/If this is bug pls report to https://github.com/BochilTeam/s craperat savefrom /home/container/node_modules/@bochilteam/sc raper/lib/cjs/social-media/savefrom.js:34:15at process.processTicksAndRejections (node:internal/process/task queues: 95:5)date: 2024-02-17T11:34:07.989Z} unhandledRejection

**Comment by Armageddonz** [comment]
Saya harap dapat diberi arahan🙏

**Comment by BochilGaming** [comment]
Try to use @bochilteam/scraper 5.0.1 version
