### ISSUE TITLE
EROR TIKTOKDL

### ISSUE THREAD

**Issue by JER-OFC** [BochilTeam/scraper#99]
HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (/home/container/node_modules/got/dist/source/as-promise/index.js:118:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1720467064387,
    socket: 1720467064389,
    lookup: 1720467064427,
    connect: 1720467064439,
    secureConnect: 1720467064459,
    upload: 1720467064459,
    response: 1720467064478,
    end: 1720467064482,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 2,
      dns: 38,
      tcp: 12,
      tls: 20,
      request: 0,
      firstByte: 19,
      download: 4,
      total: 95
    }
  }
}

**Comment by BochilGaming** [comment]
Try to use @bochilteam/scraper 5.0.1 version
